    version: "3.1"

    services:
      app:
        ports:
          - port:80
        environment:
            TZ: "Europe/Amsterdam"
        volumes:
          - ./app:/var/www/html/
          - ./cron:/var/cron/
          - ./scripts:/var/scripts/
          - ./workspace:/var/workspace
