    version: "3.1"

    services:
      app:
        ports:
          - port:80
        volumes:
          - ./app:/var/www/html/
          - ./cron:/var/cron/
          - ./scripts:/var/scripts/
          - ./workspace:/var/workspace
          - ./etc/timezone:/etc/timezone:ro
          - ./etc/localtime:/etc/localtime:ro
